export const buildings = [
	"Gedung Olahraga",
	"Gedung A",
	"Gedung B",
	"Gedung C",
	"Gedung D",
	"Gedung E",
	"Gedung F",
	"Gedung Administrasi",
	"Gedung Perpustakaan",
	"Gedung Laboratorium",
	"Gedung Komputer",
	"Gedung Bahasa",
	"Gedung Seni",
	"Gedung Musik",
	"Gedung IPA",
	"Gedung IPS",
	"Gedung TK",
	"Gedung SD",
	"Gedung SMP",
	"Gedung SMA",
];
