import { Schedule } from "@/components/page/schedule/teacher-schedule-card.tsx";

export const scheduleData: Schedule[] = [
	{
		id: 134234,
		day: "Senin",
		time: "07.00 - 08.30",
		subject: "Matematika",
		classTitle: "X IPA 1",
		totalStudent: 32,
		present: 30,
		absent: 1,
		sick: 1,
		permission: 0,
		teacher: "Ibu Sari",
		room: "Ruang 101",
	},
	{
		id: 134235,
		day: "Senin",
		time: "08.30 - 10.00",
		subject: "Bahasa Indonesia",
		classTitle: "X IPA 1",
		totalStudent: 32,
		present: 31,
		absent: 0,
		sick: 1,
		permission: 0,
		teacher: "Pak Andi",
		room: "Ruang 101",
	},
	{
		id: 134236,
		day: "Selasa",
		time: "07.00 - 08.30",
		subject: "Kimia",
		classTitle: "X IPA 1",
		totalStudent: 32,
		present: 29,
		absent: 1,
		sick: 1,
		permission: 1,
		teacher: "Ibu Rina",
		room: "Ruang 102",
	},
	{
		id: 134237,
		day: "Rabu",
		time: "07.00 - 08.30",
		subject: "Sejarah",
		classTitle: "X IPA 1",
		totalStudent: 32,
		present: 30,
		absent: 2,
		sick: 0,
		permission: 0,
		teacher: "Pak Budi",
		room: "Ruang 103",
	},
	{
		id: 134238,
		day: "Kamis",
		time: "08.30 - 10.00",
		subject: "Biologi",
		classTitle: "X IPA 1",
		totalStudent: 32,
		present: 32,
		absent: 0,
		sick: 0,
		permission: 0,
		teacher: "Ibu Lestari",
		room: "Ruang 104",
	},
	{
		id: 134239,
		day: "Jumat",
		time: "14.15 - 15.45",
		subject: "Penjaskes",
		classTitle: "X IPA 1",
		totalStudent: 32,
		present: 31,
		absent: 0,
		sick: 0,
		permission: 1,
		teacher: "Pak Hendra",
		room: "Lapangan",
	},
];
